docker:
  - source: "docker.io/kong/kubernetes-ingress-controller"
    destination: "ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/kubernetes-ingress-controller"
    tags:
      - "3.4"
  - source: "docker.io/kong"
    destination: "ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/kong"
    tags:
      - "3.9"

files:
  - source: https://download.db-ip.com/free/dbip-city-lite-2025-10.mmdb.gz
    transforms: 
     - type: "gunzip"
    destination: ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/dbip-city-lite
    tags:
      - "2025-10"
    mime: application/vnd.dbip.database


# Global settings
settings:
  # Whether to make mirrored images public (true) or private (false)
  public: true
  
  
  # Retry configuration
  retry_attempts: 3
  retry_delay: 1  # seconds
